# Generated by Django 5.1.3 on 2024-11-14 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0003_category_more_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='more_details',
        ),
    ]
